export default {
  documents: {
    // 'quick-start': require('./quick-start'),
    // 'i18n': require('./i18n'),
    // 'custom-theme': require('./custom-theme')
  },
  components: {
    Basic: {
      grid: require('./Grid'),
      layout: require('./Layout'),
      //   'color': require('./color'),
      //   'typography': require('./typography'),
      icon: require('./Icon'),
      button: require('./Button'),
      list: require('./List'),
    },
    Form: {
      radio: require('./Radio'),
      checkbox: require('./Checkbox'),
      input: require('./Input'),
      'input-number': require('./InputNumber'),
      select: require('./Select'),
      cascader: require('./Cascader'),
      switch: require('./Switch'),
      // 'slider': require('./slider'),
      'time-picker': require('./TimePicker'),
      'date-picker': require('./DatePicker'),
      // 'datetime-picker': require('./datetime-picker'),
      upload: require('./Upload'),
      rate: require('./Rate'),
      // 'color-picker': require('./color-picker'),
      // 'transfer': require('./transfer'),
      form: require('./Form'),
    },
    Data: {
      table: require('./Table'),
      tag: require('./Tag'),
      progress: require('./Progress'),
      tree: require('./Tree'),
      treeSelect: require('./TreeSelect'),
      pagination: require('./Pagination'),
      badge: require('./Badge'),
    },
    Notice: {
      alert: require('./Alert'),
      spin: require('./Spin'),
      message: require('./Message'),
      modal: require('./Modal'),
      notification: require('./Notification'),
      popconfirm: require('./Popconfirm'),
    },
    Nav: {
      menu: require('./Menu'),
      tabs: require('./Tabs'),
      breadcrumb: require('./Breadcrumb'),
      // 'dropdown': require('./dropdown'),
      steps: require('./Steps'),
      affix: require('./Affix'),
    },
    Others: {
      // 'dialog': require('./dialog'),
      tooltip: require('./Tooltip'),
      popover: require('./Popover'),
      card: require('./Card'),
      timeline: require('./TimeLine'),
      // 'carousel': require('./carousel'),
      // 'collapse': require('./collapse')
    },
    Todos: {
      // 'carousel': require('./carousel'),
      // tree: require('./Tree'),
      // badge: require('./Badge'),
      // spin: require('./Spin'),
      // cascader: require('./Cascader'),
      // switch: require('./Switch'),
      slider: require('./Slider'),
      // 'input-number': require('./InputNumber')
    },
  },
}
